### ISSUE TITLE
Update Models

### ISSUE THREAD

**Issue by jtmoulia** [DocDir/docdir#1]
Improvements to the models con tests:
- [X] Doctor through models must have `start` and `end` datetime fields. Time ranges must be non-overlapping.
- [X] Doctor through models must have a `score` float field for ranking. By default, `score` is `1` (?)
- [X] Models should have a `source` field, i.e. where is the data from. By default, the `source` is null.

**Comment by clarktheshark** [comment]
1) model verification looks like it can be handled a few different ways -> model forms, pre-save signals, overriding model save() method, and model mixin. This is ignoring pull validation as well, since there might be the case where django was not the poi into the db (thinking about crawling here). 

3) sources as different tables?

4) aren't these distinct concepts that should be separate? ie, created should exist regardless of start/end

**Comment by jtmoulia** [comment]
> model verification looks like it can be handled a few different ways -> model forms, pre-save signals, overriding model save() method, and model mixin.

I started on this last week -- it's incomplete, but should be heading in the right direction: https://github.com/DocDir/docdir/commit/990f1f71988e9139a593008aecaf94f6157eb44c. I hear you re validation being different between the app and crawlers.

We might also want a general abstract model for general fields like `created`, ... ?

> 3) sources as different tables?

What're you thinking exactly? A single other sources table, or something like the current through tables??

> 4) aren't these distinct concepts that should be separate? ie, created should exist regardless of start/end

Good point -- agreed.

**Comment by jtmoulia** [comment]
Resolved by https://github.com/DocDir/docdir/commit/cba4302c12aba78f69247d03a3e4877e55b84fba
